### ISSUE TITLE
Support for mac

### ISSUE THREAD

**Issue by RahulJanagouda** [KevinWang15/PsVDecrypt#13]
Hey, 
Impressive work!
Would you please provide support for mac as well? If not possible, I would like support offline videos for mac. Could you help me out with that? What is the core logic for the decryption?
Thanks

**Comment by KevinWang15** [comment]
Sorry, since I don't have a Mac computer there's currently no support for Mac, 
I haven't reverse engineered the Mac client so I'm not sure how it's implemented.

I explained how I did it on windows in #12.
in #10 I suggested that if you are using a Mac, you may try using Boot Camp or launch a windows VM on AWS.

On windows I used dotPeek to decompile the C# offline player, if the offline player in Mac is also C#, it should be easy.
